<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Problem 2 from Project Euler | PHP</title>
	</head>
	<body>

		<?php

/*

Problem: https://projecteuler.net/problem=2
 
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Code by Tom Tillistrand

*/

$term_one = 1;
$term_two = 2;
$total = 0;

for($i = 0; $term_one < 4000000; $i++){
	
	if($term_one % 2 === 0){
		$total += $term_one;
	}
	
	$temp = $term_two;
	$term_two = $term_one + $term_two;
	$term_one = $temp;
}

echo "The sum of all the even-valued terms in the Fibonacci sequence that do not exceed 4,000,000 is $total";

?>
	</body>
</html>